-- Local Oracle Database Free schema.
-- The local dataset is small enough for exact VECTOR_DISTANCE scans, so HNSW indexes are
-- intentionally omitted. Oracle Free starts with vector_memory_size=0, while production ATP
-- provides a vector memory area for the indexes in ai-worker/src/main/resources/oracle-schema.sql.

CREATE TABLE IF NOT EXISTS job_posting_vector (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_posting_id NUMBER NOT NULL,
    chunk_content CLOB NOT NULL,
    embedding_vector VECTOR(2048, FLOAT32) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS experience_vector (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id NUMBER NOT NULL,
    experience_id NUMBER NOT NULL,
    chunk_content CLOB NOT NULL,
    embedding_vector VECTOR(2048, FLOAT32) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

DECLARE
    column_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO column_count
    FROM user_tab_columns
    WHERE table_name = 'EXPERIENCE_VECTOR' AND column_name = 'WORKSPACE_ID';
    IF column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE experience_vector ADD workspace_id NUMBER DEFAULT 1 NOT NULL';
    END IF;
END;
/

CREATE TABLE IF NOT EXISTS study_vector (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id NUMBER NOT NULL,
    study_id NUMBER NOT NULL,
    chunk_content CLOB NOT NULL,
    embedding_vector VECTOR(2048, FLOAT32) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

DECLARE
    column_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO column_count
    FROM user_tab_columns
    WHERE table_name = 'STUDY_VECTOR' AND column_name = 'WORKSPACE_ID';
    IF column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE study_vector ADD workspace_id NUMBER DEFAULT 1 NOT NULL';
    END IF;
END;
/

CREATE INDEX IF NOT EXISTS idx_study_vector_workspace_study
ON study_vector (workspace_id, study_id);
