-- Local Oracle Database Free schema.
-- The local dataset is small enough for exact VECTOR_DISTANCE scans, so HNSW indexes are
-- intentionally omitted. Oracle Free starts with vector_memory_size=0, while production ATP
-- provides a vector memory area for the indexes in ai-worker/src/main/resources/oracle-schema.sql.

CREATE TABLE IF NOT EXISTS job_posting_vector (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_posting_id NUMBER NOT NULL,
    chunk_content CLOB NOT NULL,
    embedding_vector VECTOR(2048, FLOAT32) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS experience_vector (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    experience_id NUMBER NOT NULL,
    chunk_content CLOB NOT NULL,
    embedding_vector VECTOR(2048, FLOAT32) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS study_vector (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_id NUMBER NOT NULL,
    chunk_content CLOB NOT NULL,
    embedding_vector VECTOR(2048, FLOAT32) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
