---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-credentials
  namespace: self-intro
spec:
  encryptedData:
    RABBITMQ_PASSWORD: AgDGqSByxF/FFxAytrfAJZpkSKuz433hSaVYRjEMXaROOzEnmxHIAJ19C6yXmjt6KES1R/H0DpszKg2NAS7BCn8Uo6ItF6+RyPPFNDJimH04K3CT1nCmqvk5NpOPGYw8Ks5uUaSYlsxXES3Ja8STlmZB5NZvGJ9wjcfVHQdTDSkZCRML+gevwn0kh0wjA35pDCKoIsql8CbYHQMbKX0n2P+UJEx1p2mz/Ww8LP3IN0livjfELhk2tDcdGtvGBnj7E2f34i2NKVaC+9DWrdakxwMNGUv9QjW+dH7gCB5tb0lruDBgLpzklRPYPiDSp63n3/cFs8YftKolbtq84nrZdQF1bEV7/5yC2iCJDMLfKsnQbhjotPSH4etmz+74FGDSwGzEeCZuxb/U3DP563uv+7STSflM1MP+7rmTiMzf7rMVIms6wJ9Hv/SkfRKpFRQQHs9OrkmI8yExxj3GSpDJh0hL6qiB3nDdh+JanCqUnCucOwO1jlLqcSdG7SNiD/dubvXfxJ6rC7QRBolWHKePvPF2M/Y3sGJuROS/hbuypWelyRKJ4hvBGR2J8ui0JZLzrLVWiyPqcCdavkpwIUDmknMf60nQXg/dZzIJJlDEAcG+c1a6Oww8dRAP3VdjNmdLZ1xbain6h3eWXelhk690FqysxVmI9FLj+Oa/HKFfVLgplL279wy6i/6CKvm5RdUU0hryjBfED/30tpgieMmb9nO1SDXP2JEMKZpbRp9D4LD07i7ZB5P9BmNrTcIjsDL67imf9w2+SrD9OOBccYRAA2gH
    RABBITMQ_USERNAME: AgDWuMrZCcr5RKmMeuWXze3Xv1z7HCqLvGhpvxMVDgVgVeQ9sz++Xl2cUoYoSjL4py5pteLK5XK9jaZdU2/RRFgOmYnaWNE0tVXCXDOIQL+GzwIMVyQUENAphtnmX3hylgBLvwwJ0oTKC46AJ5a4D+MoCkenyCTWrQBa1WSUdW6tku3YSUx62Tw2jNuSKTKReCYhOIFqwNeuijbQBD7QUHrg06ik4NV+Monwo8K/rVctubbxrXnelHHw7am83bv6dh7iidc24m2FCOw1AOWFcvJd1WhQPFsfGZKId6DIMSWXLkND7AyEqDHX0cbWXF5d956c0JUfboZGxt1iOj2rN26yPBlvlz8YQ1+x58Iuz+m7Cr3aAqFU1SczG0xPI/f6cr67GQoxzJ+Dz5yf04HO0nMLwayM8HgntF5eaLdN7vzfbn6hGhSJZopr4zw7TucgHLQVf8mNx6MMdU+rUz6eHvhvwKAgcYybxR0T8X67x/NHYGZfOD6Vnrcgf194736nz5qq7QicjlRDij7XBP4ne2p7G2JlmgrCY/8QFsZfgiMoerj0HKKxSxcQMICwLijZNO6ZnoGCPpcbKh+K1baRK7Nk4f/kwR+MBzk3/kbuTrh+v/mtm6FvnhmdQ2N9lpo86gJPL/kJ38pZ/YQ9ZRmFwoMJHHngSfy4s3Md5pnsXRxVhozM3NKWi/KC40qHxof4hhyL8ehtLZyk12c=
  template:
    metadata:
      name: rabbitmq-credentials
      namespace: self-intro
