apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: self-intro

resources:
  - ../../../base/frontend
  - ingress.yaml

images:
  - name: self-intro-frontend
    newName: yny.ocir.io/axrywc89b6lf/self-intro/frontend
    newTag: "a9a8487"
