apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: self-intro-backend-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: REPLACE_WITH_GIT_REPOSITORY_URL
    targetRevision: main
    path: deploy/k8s/overlays/prod/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: self-intro
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
