package com.selfintro.modules.learningresource.application;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.when;

import com.selfintro.modules.learningresource.domain.entity.LearningResource;
import com.selfintro.modules.learningresource.domain.enums.LearningResourceRelationType;
import com.selfintro.modules.learningresource.domain.enums.LearningResourceStatus;
import com.selfintro.modules.learningresource.domain.enums.LearningResourceType;
import com.selfintro.modules.learningresource.domain.repository.LearningResourceRepository;
import com.selfintro.modules.learningresource.presentation.dto.LearningResourceRelationRequest;
import com.selfintro.modules.learningresource.presentation.dto.LearningResourceRequest;
import com.selfintro.modules.skill.domain.repository.SkillRepository;
import com.selfintro.modules.study.domain.entity.Tag;
import com.selfintro.modules.study.domain.repository.TagRepository;
import com.selfintro.modules.taxonomy.domain.entity.TaxonomyNode;
import com.selfintro.modules.taxonomy.domain.repository.TaxonomyNodeRepository;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.test.util.ReflectionTestUtils;

@ExtendWith(MockitoExtension.class)
class LearningResourceServiceTest {

    @Mock LearningResourceRepository learningResourceRepository;
    @Mock TaxonomyNodeRepository taxonomyNodeRepository;
    @Mock TagRepository tagRepository;
    @Mock SkillRepository skillRepository;

    private LearningResourceService service;
    private TaxonomyNode taxonomyNode;

    @BeforeEach
    void setUp() throws Exception {
        service =
                new LearningResourceService(
                        learningResourceRepository,
                        taxonomyNodeRepository,
                        tagRepository,
                        skillRepository);
        var constructor = TaxonomyNode.class.getDeclaredConstructor();
        constructor.setAccessible(true);
        taxonomyNode = constructor.newInstance();
        ReflectionTestUtils.setField(taxonomyNode, "id", 1L);
        ReflectionTestUtils.setField(taxonomyNode, "name", "백엔드 코어");
        ReflectionTestUtils.setField(taxonomyNode, "slug", "backend-core");
    }

    private LearningResourceRequest newRequest(
            List<Long> taxonomyNodeIds,
            List<String> tagNames,
            List<LearningResourceRelationRequest> relatedResources) {
        return new LearningResourceRequest(
                null,
                "Real MySQL 시즌 1 - Part 1",
                LearningResourceType.ONLINE_COURSE,
                "인프런",
                "https://www.inflearn.com/course/real-mysql-part-1",
                "이도경",
                209,
                LearningResourceStatus.WISHLIST,
                null,
                0,
                taxonomyNodeIds,
                null,
                null,
                tagNames,
                List.of(),
                relatedResources);
    }

    @Test
    void createsResourceWithAutoGeneratedSlugAndResolvedTags() {
        when(taxonomyNodeRepository.findAllById(List.of(1L))).thenReturn(List.of(taxonomyNode));
        when(learningResourceRepository.existsBySlug(any())).thenReturn(false);
        when(tagRepository.findByNameIgnoreCase("MySQL")).thenReturn(Optional.empty());
        when(tagRepository.save(any(Tag.class)))
                .thenAnswer(invocation -> invocation.getArgument(0));
        when(learningResourceRepository.save(any(LearningResource.class)))
                .thenAnswer(invocation -> invocation.getArgument(0));

        var response = service.create(newRequest(List.of(1L), List.of("MySQL"), List.of()));

        assertThat(response.title()).isEqualTo("Real MySQL 시즌 1 - Part 1");
        assertThat(response.slug()).isNotBlank();
        assertThat(response.status()).isEqualTo(LearningResourceStatus.WISHLIST);
        assertThat(response.tags()).extracting("name").containsExactly("MySQL");
    }

    @Test
    void slugFallsBackToSuffixWhenAlreadyTaken() {
        when(taxonomyNodeRepository.findAllById(List.of(1L))).thenReturn(List.of(taxonomyNode));
        when(learningResourceRepository.existsBySlug("real-mysql-시즌-1-part-1")).thenReturn(true);
        when(learningResourceRepository.existsBySlug("real-mysql-시즌-1-part-1-2")).thenReturn(false);
        when(learningResourceRepository.save(any(LearningResource.class)))
                .thenAnswer(invocation -> invocation.getArgument(0));

        var response = service.create(newRequest(List.of(1L), List.of(), List.of()));

        assertThat(response.slug()).isEqualTo("real-mysql-시즌-1-part-1-2");
    }

    @Test
    void rejectsSelfRelation() {
        when(taxonomyNodeRepository.findAllById(List.of(1L))).thenReturn(List.of(taxonomyNode));
        when(learningResourceRepository.existsBySlug(any())).thenReturn(false);

        LearningResource[] savedHolder = new LearningResource[1];
        when(learningResourceRepository.save(any(LearningResource.class)))
                .thenAnswer(
                        invocation -> {
                            LearningResource resource = invocation.getArgument(0);
                            ReflectionTestUtils.setField(resource, "id", 10L);
                            savedHolder[0] = resource;
                            return resource;
                        });
        when(learningResourceRepository.findById(10L))
                .thenAnswer(invocation -> Optional.ofNullable(savedHolder[0]));

        var request =
                newRequest(
                        List.of(1L),
                        List.of(),
                        List.of(
                                new LearningResourceRelationRequest(
                                        10L, LearningResourceRelationType.RELATED)));

        assertThatThrownBy(() -> service.create(request))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("cannot be related to itself");
    }
}
