-- Oracle 26ai Vector Search & MSA Dual DB 아키텍처 (MySQL + Oracle ATP) 심층 스터디 노트 추가.

INSERT INTO `study` (`slug`, `title`, `summary`, `content_markdown`, `status`, `category_id`, `learned_at`, `published_at`, `created_at`, `updated_at`)
VALUES (
  'oracle-26ai-vector-search-msa-dual-db-architecture',
  'Oracle 26ai Vector Search 및 MSA Dual DB 아키텍처 (MySQL × Oracle ATP) 구축 가이드',
  '메인 백엔드 CRUD용 기존 MySQL 8.0과 AI Worker 전용 Oracle Autonomous Database (26ai)를 이원화(Dual DB)하고, Oracle 26ai의 Native VECTOR 데이터 타입 및 VECTOR_DISTANCE 코사인 유사도 검색을 활용하여 채용공고 시맨틱 검색 아키텍처를 구축한 과정을 정리합니다.',
  '# Oracle 26ai Vector Search 및 MSA Dual DB 아키텍처 (MySQL × Oracle ATP) 구축 가이드

## 1. 개요: 왜 Dual DB (MySQL + Oracle 26ai) 구조인가?

운영 중인 백엔드 시스템에 AI 임베딩 벡터 검색(Vector Search / Semantic Search)을 도입할 때, 기존 메인 데이터베이스(MySQL 8.0)를 전체 마이그레이션하지 않고 **MSA(Microservice Architecture) 원칙에 따라 역할을 분리**하는 이원화 DB 아키텍처를 선택했습니다.

| 구분 | API Microservice (:api) | Worker Microservice (:ai-worker) |
| :--- | :--- | :--- |
| **역할** | 유저, 경험, 스터디, 자소서 기본 CRUD 및 조회 | AI 채용공고 수집, 텍스트 벡터화, 시맨틱 검색 |
| **데이터베이스** | **MySQL 8.0** (기존 인프라 유지) | **Oracle Autonomous DB 26ai** (신규 구축) |
| **접속 방식** | OCI VCN Private Subnet Direct JDBC | OCI ATP Wallet (mTLS 보안 인증서) |
| **특징** | 고성능 트랜잭션 (OLTP) | **Native VECTOR 타입 & VECTOR_DISTANCE 쿼리** |

---

## 2. Oracle 26ai Vector Search 동작 메커니즘

Oracle Database 26ai는 **`VECTOR`라는 Native 데이터 타입**과 코사인 유사도, 유클리디안 거리 등의 거리 계산 함수를 기본 탑재하고 있습니다.

### 1) DDL 스키마 정의 (`VECTOR` 타입)

```sql
CREATE TABLE job_posting_vector (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_posting_id NUMBER NOT NULL,
    chunk_content CLOB NOT NULL,
    embedding_vector VECTOR(1536, FLOAT32) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
```

### 2) 코사인 유사도 검색 PromQL / SQL 쿼리

`VECTOR_DISTANCE(..., COSINE)` 함수를 통해 사용자 자가소개서와 가장 유사한 채용공고 텍스트 청크를 0.001초 이내에 검색합니다:

```sql
SELECT v.*
FROM job_posting_vector v
ORDER BY VECTOR_DISTANCE(v.embedding_vector, to_vector(:queryVector), COSINE) ASC
FETCH FIRST :limit ROWS ONLY;
```

---

## 3. K8s 파드 독립화 & Wallet 보안 연동

### 1) mTLS Wallet Volume Mount

Oracle ATP는 강화된 보안을 위해 **mTLS(mutual TLS)** 전자 지갑(Wallet) 인증서를 요구합니다. 이를 K8s Secret으로 등록하고 Pod에 투명하게 마운트합니다.

```yaml
spec:
  containers:
    - name: backend-worker
      image: self-intro-backend-worker
      volumeMounts:
        - name: oracle-atp-wallet
          mountPath: /etc/oracle/wallet
          readOnly: true
  volumes:
    - name: oracle-atp-wallet
      secret:
        secretName: oracle-atp-worker-wallet
```

### 2) JDBC URL 설정 (TNS_ADMIN)

`TNS_ADMIN=/etc/oracle/wallet` 파라미터를 통해 Java 애플리케이션이 마운트된 Wallet 경로의 인증서를 자동으로 읽어들입니다:

```
jdbc:oracle:thin:@selfintroworker_high?TNS_ADMIN=/etc/oracle/wallet
```

---

## 4. 파드별 독립 Dockerfile & CI/CD 파이프라인

독립적인 확장성(Scalability)과 빠른 빌드 타임을 위해 Dockerfile과 GitHub Actions 파이프라인을 완전 분리했습니다.

```
.github/workflows/
  ├─ deploy-api.yml     (backend/api/** 소스 변경 시 API 파드만 빌드)
  └─ deploy-worker.yml  (backend/ai-worker/** 소스 변경 시 Worker 파드만 빌드)
```

- **`Dockerfile.api`**: REST API 및 Playwright 브라우저 포함 이미지
- **`Dockerfile.worker`**: AI Worker 및 Oracle JDBC (`ojdbc11`) 호환 경량화 이미지

---

## 5. 핵심 요약 (Key Takeaways)

- **Dual DB 패턴**: 메인 CRUD(MySQL)와 AI Vector Search(Oracle 26ai)의 역할을 명확히 분리하여 기존 서비스 안정성 보장.
- **Oracle 26ai Native Vector**: 별도 외부 Vector DB 설치 없이 Oracle 내장 `VECTOR` 타입 및 `VECTOR_DISTANCE` 함수 활용.
- **K8s mTLS Wallet**: `oracle-atp-worker-wallet` K8s Secret 마운트로 보안성 제고 및 설정 투명화.
- **독립 CI/CD**: API 서비스와 AI Worker 서비스의 빌드/배포 파이프라인을 분리하여 신속한 피드백 루프 확보.',
  'PUBLISHED',
  5,
  '2026-08-02',
  NOW(),
  NOW(), NOW()
);

SET @study_id = LAST_INSERT_ID();

-- 관련 태그 연결 (Architecture, Docker, Kubernetes, DevOps)
INSERT INTO `study_tag` (`study_id`, `tag_id`)
SELECT @study_id, `id` FROM `tag` WHERE `name` IN ('Architecture', 'Docker', 'Kubernetes', 'DevOps')
ON DUPLICATE KEY UPDATE `study_id` = `study_id`;

-- 관련 스킬 연결 (Kubernetes, Docker)
INSERT INTO `study_skill` (`study_id`, `skill_id`)
SELECT @study_id, `id` FROM `skill` WHERE `name` IN ('Kubernetes', 'Docker')
ON DUPLICATE KEY UPDATE `study_id` = `study_id`;

-- 이전 모니터링 스터디(V144)와 연관 관계 설정
INSERT INTO `study_related` (`study_id`, `related_study_id`, `relation_type`)
SELECT @study_id, `id`, 'RELATED' FROM `study` WHERE `slug` = 'kubernetes-node-exporter-grafana-dashboard-deep-dive'
ON DUPLICATE KEY UPDATE `study_id` = `study_id`;
