-- V148: V145 'oracle-26ai-vector-search-msa-dual-db-architecture' 스터디 내용 보강
-- 실제 JPA Entity (VECTOR 타입 매핑), Repository (VECTOR_DISTANCE 네이티브 쿼리),
-- K8s Wallet Volume Mount, AI Worker application.yml H2 → Oracle 자동 전환, Batch Sync Pipeline 구현 코드 반영

UPDATE `study`
SET `content_markdown` = '# Oracle 26ai Vector Search 및 MSA Dual DB 아키텍처 (MySQL × Oracle ATP) 구축 가이드

## 1. 개요: 왜 Dual DB (MySQL + Oracle 26ai) 구조인가?

운영 중인 백엔드 시스템에 AI 임베딩 벡터 검색(Vector Search / Semantic Search)을 도입할 때, 기존 메인 데이터베이스(MySQL 8.0)를 전체 마이그레이션하지 않고 **MSA(Microservice Architecture) 원칙에 따라 역할을 분리**하는 이원화 DB 아키텍처를 선택했습니다.

| 구분 | API Microservice (:api) | Worker Microservice (:ai-worker) |
| :--- | :--- | :--- |
| **역할** | 유저, 경험, 스터디, 자소서 기본 CRUD 및 조회 | AI 채용공고 수집, 텍스트 벡터화, 시맨틱 검색 |
| **데이터베이스** | **MySQL 8.0** (기존 인프라 유지) | **Oracle Autonomous DB 26ai** (신규 구축) |
| **접속 방식** | OCI VCN Private Subnet Direct JDBC | OCI ATP Wallet (mTLS 보안 인증서) |
| **특징** | 고성능 트랜잭션 (OLTP) | **Native VECTOR 타입 & VECTOR_DISTANCE 쿼리** |

---

## 2. Oracle 26ai Vector Search 동작 메커니즘

Oracle Database 26ai는 **`VECTOR`라는 Native 데이터 타입**과 코사인 유사도, 유클리디안 거리 등의 거리 계산 함수를 기본 탑재하고 있습니다.

### 2-1. DDL 스키마 정의 (`oracle-schema.sql`)

3개 도메인(채용공고, 경험, 스터디) 벡터 테이블과 HNSW 코사인 인덱스를 정의합니다.

```sql
-- 채용공고 벡터 테이블
CREATE TABLE job_posting_vector (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_posting_id NUMBER NOT NULL,
    chunk_content CLOB NOT NULL,
    embedding_vector VECTOR(1536, FLOAT32) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_job_posting_vector_hnsw
ON job_posting_vector (embedding_vector)
ORGANIZATION INMEMORY NEIGHBOR GRAPH
DISTANCE COSINE;

-- 경험 벡터 테이블
CREATE TABLE experience_vector (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    experience_id NUMBER NOT NULL,
    chunk_content CLOB NOT NULL,
    embedding_vector VECTOR(1536, FLOAT32) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 스터디 벡터 테이블
CREATE TABLE study_vector (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_id NUMBER NOT NULL,
    chunk_content CLOB NOT NULL,
    embedding_vector VECTOR(1536, FLOAT32) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
```

### 2-2. JPA Entity의 Oracle VECTOR 타입 매핑 (`JobPostingVector.java`)

Oracle 26ai의 `VECTOR(1536, FLOAT32)` 데이터 타입을 JPA `@Column(columnDefinition = \"VECTOR\")`으로 매핑합니다. 임베딩 벡터는 `\"[0.012, -0.045, ...]\"` 문자열 형태로 저장됩니다.

```java
@Entity
@Table(name = \"job_posting_vector\")
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class JobPostingVector {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = \"job_posting_id\", nullable = false)
    private Long jobPostingId;

    @Column(name = \"chunk_content\", columnDefinition = \"CLOB\", nullable = false)
    private String chunkContent;

    /**
     * Oracle 26ai VECTOR 데이터 타입 (1536차원 임베딩 수치 배열 문자열)
     */
    @Column(name = \"embedding_vector\", columnDefinition = \"VECTOR\", nullable = false)
    private String embeddingVector;

    @Column(name = \"created_at\", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Builder
    public JobPostingVector(Long jobPostingId, String chunkContent, String embeddingVector) {
        this.jobPostingId = jobPostingId;
        this.chunkContent = chunkContent;
        this.embeddingVector = embeddingVector;
        this.createdAt = LocalDateTime.now();
    }
}
```

### 2-3. VECTOR_DISTANCE 네이티브 쿼리 (`JobPostingVectorRepository.java`)

`@Query(nativeQuery = true)`로 Oracle 26ai 전용 `VECTOR_DISTANCE` 함수를 직접 호출합니다. 코사인 거리(Distance)가 0에 가까울수록 가장 유사한 문서입니다.

```java
public interface JobPostingVectorRepository extends JpaRepository<JobPostingVector, Long> {

    List<JobPostingVector> findByJobPostingId(Long jobPostingId);
    void deleteByJobPostingId(Long jobPostingId);

    /**
     * Oracle 26ai VECTOR_DISTANCE 코사인 유사도 Top-K 검색
     */
    @Query(value = \"SELECT v.* FROM job_posting_vector v \" +
                   \"ORDER BY VECTOR_DISTANCE(v.embedding_vector, \" +
                   \"to_vector(:queryVector), COSINE) ASC \" +
                   \"FETCH FIRST :limit ROWS ONLY\", nativeQuery = true)
    List<JobPostingVector> searchTopKSimilarChunks(
        @Param(\"queryVector\") String queryVector, @Param(\"limit\") int limit);
}
```

---

## 3. AI Worker 로컬/운영 환경 자동 전환

AI Worker의 `application.yml`은 환경변수 유무에 따라 **로컬 H2 ↔ 운영 Oracle ATP**를 자동 전환합니다.

```yaml
spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:workerdb;MODE=Oracle}    # 로컬: H2 Oracle 호환 모드
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}       # 운영: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
```

- **로컬 개발**: H2 인메모리 DB (`MODE=Oracle`)로 Oracle 방언을 에뮬레이션하여 로컬 개발 시 Oracle 설치 없이 테스트 가능.
- **K8s 운영**: 환경변수로 Oracle ATP JDBC URL(`jdbc:oracle:thin:@selfintroworker_high?TNS_ADMIN=/etc/oracle/wallet`)을 주입.

---

## 4. K8s 파드 독립화 & Wallet 보안 연동

### 4-1. mTLS Wallet Volume Mount

Oracle ATP는 강화된 보안을 위해 **mTLS(mutual TLS)** 전자 지갑(Wallet) 인증서를 요구합니다. 이를 K8s Secret으로 등록하고 Pod에 투명하게 마운트합니다.

```yaml
spec:
  containers:
    - name: backend-worker
      image: self-intro-backend-worker
      ports:
        - name: grpc
          containerPort: 9090
        - name: http
          containerPort: 8081
      envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-worker-db-secret
        - secretRef:
            name: backend-ai-secret
      env:
        - name: JOB_POSTING_SCHEDULER_ENABLED
          value: \"true\"
      volumeMounts:
        - name: oracle-atp-wallet
          mountPath: /etc/oracle/wallet
          readOnly: true
      resources:
        requests:
          cpu: 250m
          memory: 768Mi
        limits:
          cpu: \"1\"
          memory: 2Gi
  volumes:
    - name: oracle-atp-wallet
      secret:
        secretName: oracle-atp-worker-wallet
        optional: true
```

### 4-2. JDBC URL 설정 (TNS_ADMIN)

`TNS_ADMIN=/etc/oracle/wallet` 파라미터를 통해 Java 애플리케이션이 마운트된 Wallet 경로의 인증서를 자동으로 읽어들입니다:

```
jdbc:oracle:thin:@selfintroworker_high?TNS_ADMIN=/etc/oracle/wallet
```

### 4-3. Recreate 배포 전략

단일 VM 노드(Oracle Cloud Free Tier)에서 CPU 경합으로 인한 OOM을 방지하기 위해, `RollingUpdate` 대신 **`Recreate`** 전략을 적용합니다. 구버전 Pod가 완전히 종료된 후 신버전을 시작하여 CPU 자원 중복 사용을 차단합니다.

```yaml
spec:
  replicas: 1
  strategy:
    type: Recreate   # 구버전 완전 종료 후 신버전 기동
  revisionHistoryLimit: 3
```

---

## 5. 파드별 독립 Dockerfile & CI/CD 파이프라인

독립적인 확장성(Scalability)과 빠른 빌드 타임을 위해 Dockerfile과 GitHub Actions 파이프라인을 완전 분리했습니다.

```
.github/workflows/
  ├─ deploy-api.yml     (backend/api/** 소스 변경 시 API 파드만 빌드)
  └─ deploy-worker.yml  (backend/ai-worker/** 소스 변경 시 Worker 파드만 빌드)
```

- **`Dockerfile.api`**: REST API 및 Playwright 브라우저 포함 이미지
- **`Dockerfile.worker`**: AI Worker 및 Oracle JDBC (`ojdbc11`) 호환 경량화 이미지

---

## 6. 1536차원 임베딩 벡터 변환 (`VectorEmbeddingService.java`)

OpenAI `text-embedding-3-small` API를 호출하여 텍스트를 1536차원 `float[]` 배열로 변환하고, Oracle 26ai VECTOR 호환 문자열 `\"[0.012, -0.045, ...]\"` 형식으로 포맷팅합니다.

```java
@Service
public class VectorEmbeddingService {

    private final EmbeddingModel embeddingModel;

    /**
     * Oracle 26ai VECTOR 호환 문자열 변환: \"[0.012345, -0.045678, ...]\"
     */
    public String embedToVectorString(String text) {
        float[] embedding = embeddingModel.embed(text);
        if (embedding != null && embedding.length > 0) {
            return formatAsOracleVectorString(embedding);
        }
        return generateFallbackVectorString(text); // 로컬: 해시 기반 결정론적 폴백
    }

    private String formatAsOracleVectorString(float[] vector) {
        StringBuilder sb = new StringBuilder(\"[\");
        for (int i = 0; i < vector.length; i++) {
            sb.append(String.format(Locale.US, \"%.6f\", vector[i]));
            if (i < vector.length - 1) sb.append(\",\");
        }
        return sb.append(\"]\").toString();
    }
}
```

**폴백 전략**: API 호출 실패 시 텍스트 해시 기반 **결정론적 1536차원 단위벡터**를 생성하여 로컬/테스트 환경에서도 파이프라인이 중단되지 않도록 합니다.

---

## 7. 핵심 요약 (Key Takeaways)

- **Dual DB 패턴**: 메인 CRUD(MySQL)와 AI Vector Search(Oracle 26ai)의 역할을 명확히 분리하여 기존 서비스 안정성 보장.
- **Oracle 26ai Native Vector**: 별도 외부 Vector DB 설치 없이 Oracle 내장 `VECTOR` 타입 및 `VECTOR_DISTANCE` 함수 활용.
- **JPA Entity VECTOR 매핑**: `@Column(columnDefinition = \"VECTOR\")`로 1536차원 임베딩을 문자열 형태로 저장.
- **VECTOR_DISTANCE 네이티브 쿼리**: JPA `@Query(nativeQuery = true)`로 코사인 유사도 Top-K 검색을 직접 실행.
- **H2 Oracle 호환 모드**: 로컬 환경에서는 `MODE=Oracle` H2로 Oracle 방언 에뮬레이션, 운영에서는 환경변수로 Oracle ATP 자동 전환.
- **K8s mTLS Wallet**: `oracle-atp-worker-wallet` K8s Secret 마운트로 보안성 제고 및 설정 투명화.
- **Recreate 배포 전략**: 단일 VM 노드의 CPU 경합을 방지하기 위해 구버전 완전 종료 후 신버전 기동.
- **임베딩 폴백 전략**: 텍스트 해시 기반 결정론적 단위벡터 생성으로 로컬/테스트 환경 파이프라인 무중단 보장.',
    `summary` = '메인 백엔드 CRUD용 기존 MySQL 8.0과 AI Worker 전용 Oracle Autonomous Database (26ai)를 이원화(Dual DB)하고, JPA Entity의 VECTOR 타입 매핑(@Column columnDefinition VECTOR), VECTOR_DISTANCE 네이티브 쿼리 기반 코사인 유사도 Top-K 검색, H2 Oracle 호환 모드 자동 전환, K8s mTLS Wallet Volume Mount, Recreate 배포 전략 및 1536차원 임베딩 폴백 전략을 실제 구현 코드와 함께 정리합니다.',
    `updated_at` = NOW()
WHERE `slug` = 'oracle-26ai-vector-search-msa-dual-db-architecture';
