---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: self-intro
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgBqfVQq1N7bN6MN2BH865rr1sbMCT+WbCdY8c0gxvdMIo43fcKZnNr8ikCbIruFc8vXU0wcDz/0tJUobFtpyx95EGM23MqcnXEcLYHtsWxUB8Lfdwcccqx3CSlejdQ7e2LL6VP7fcp3Lap9UFOC7QoZHKdAsW0bRVmNiLExLV7DPebtlDBd4WbUHcczgF2LutsOQYOg9kjxKfKDOHIgaPqn8yYmC3H5ay19dLRd+xs4nnK88Wlp6DLsauKJ9sBgxoMyB3OotwhpbKEVYhN5sN/vPag2AH92xUrvSp/vidDzNv1ujLiAdWWXXv1S64sWLFF90nHg4w8Hpl25DP+82MhiGiMwW01ZL+gqNdKyvZcLNlcYM1628k5zzDmrQcEQxhiyLjfAUAjMjxu2BF3yyfPqAMKhD1EqTR7/nbal7/Q4r7obHaJLkWge7qICZzKNID44t1WN55IU8Qos8XWrArLfOxmsbnvtn8vUA5u3OrvEn8FYTDAflwI7iGyoMwyXXsmF6TKp9RDTo6BtpWJCgoE8ttVjFr9dOLW0q7v5MMB75U+aLzFcbnw7p4fAGX56GL6m8Sxu6TnaLvroM7QMvwVq6oY/UEIRys6l/HzzzaLOLuLr7GA+rQwifflf3hnXdK2mE9JT5SzR/WVqRcvwy/dh0fo3upUOVzH8I3PQ5NHhn0YFghZl/4beosqPVg9hzydOnB1jI0hM0oxRGg==
    GF_SECURITY_ADMIN_USER: AgAJiTdeexvE93qisdqsexQkhV01PGSjONSQebDYWV4YJYwKP0co7qS7A/IB9gL13zGIE/LJy57kzQ9Xb2TInUPTSbZJAdptdrj1wUNAwRocKNlPNNoCKyca1qq5ItFTO5gSH+X6LjQU/XYHtClReXBP8RAcgb2qK95BhahEVyniTuzfzGfapw2Felph8iI3Cpu7mZmSQrv96Sd2VO6RwNgNyx3YZXKN6dURozld4nSOQwjm0AYOWP0Bw/Jmvdo/Z5GDrW4gO+ZZFrIguquS/W/cxKhpG1FvrbxCtE8Yof/xVQV91Ft4irpN7EIGsRPNpFHjn6afA2UFSpmHnM2kGE7+qPcneRzkZ5QDyG9o9q1LBFC9zR7867D+v/p4mkH4Upx14v4Hz3U3tC6/eav1GwaG3P6hAtKV6cxkJOtLPcLC0DjCU5wjKIgIzCYG8rH92MsLSGyvVLCRbZx82KjFVcbCRXLbzS58fjPFWUKbsd7Ah0KygZutOq0/61mikWQ00Lm2q7RAOzKchwWSkcIahPocA3taDtl3w67YhCZnRJ6K0+DAy29UIGayVTMd7UTdu/2eGIl5zx03iR/S1IfC1EpuIsXPho2EZ8tsHsZrbLk5+fsBPMHHmwk1l0nZZBlLSDUORuyjc4LoVUe53cHaRnmMiVQJlcqVlU11k+KXWTRqkhHPk/1h9zOS1SwvUBX3+orwdPtXUKTV+t6u
  template:
    metadata:
      name: grafana-admin-secret
      namespace: self-intro
    type: Opaque
