-- V45: Update Study Markdown Contents to Technical Deep-Dive Structure

UPDATE study SET content_markdown = '# AI 튜터 메시징 대화형 세션 아키텍처 설계 및 구현\n\n## 1. 기술 배경 및 해결하고자 한 핵심 문제\n- 커리큘럼 기반 AI 학습 플랫폼에서 학생들에게 학습 컨텍스트별 맞춤형 AI 피드백을 제공하기 위해 대화형 메시징 세션 엔진이 요구되었습니다.\n- 문제풀이, 오답 복습, 챌린지, 개념 보강 등 서로 다른 4가지 학습 도메인이 하나의 평평한 모델에 혼재되어 있어, 컨텍스트 추가 시 비즈니스 변경 여파가 크고 외부 LLM 통신의 Latency 지연으로 인한 스레드 병목 위험이 존재했습니다.\n\n## 2. 기술 동작 원리 및 아키텍처 설계\n- **팩토리 패턴 기반 도메인 추상화 (`AiTutorSessionFactory`)**:\n  - 4종의 다형적인 학습 컨텍스트 엔티티를 단일 대화형 세션 모델로 안전하게 변환할 수 있는 도메인 팩토리 아키텍처를 설계했습니다.\n- **SQS 기반 이벤트 비동기 파이프라인**:\n  - 외부 LLM 서버와의 네트워크 지연 차단을 위해 메시지 발행/구독(Pub/Sub) 아키텍처를 적용했습니다.\n  - SQS 메시지 재처리(Retry) 발생 시 동일 메시지가 중복 처리되지 않도록 Redis 멱등키(Idempotence Key) 검증 로직을 도입했습니다.\n- **MongoDB Replica Set 분산 트랜잭션**:\n  - 세션 대화 로그 및 상태 전이가 데이터 유실 없이 원자적(Atomic)으로 기록되도록 Multi-Document 트랜잭션을 구성했습니다.\n- **BFF (Backend for Frontend) 게이트웨이**:\n  - NestJS 기반 BFF 서버를 통해 HTML Sanitize 처리 및 커서 기반 페이지네이션 조회 성능을 최적화했습니다.\n\n## 3. 핵심 구현 및 트러블슈팅 인사이트\n- **도메인 격리 인사이트**: 학습 컨텍스트 추상화를 통해 신규 학습 기능 추가 시 기존 AI 메시징 파이프라인의 수정 없이 결합도를 낮출 수 있었습니다.\n- **비동기 멱등성 보장**: 네트워크 유실로 인한 SQS 재시도 시에도 Redis Atomic INCR 및 TTL 멱등 체크를 통해 세션 상태의 무결성을 유지했습니다.'
WHERE slug = 'ai-tutor-session-architecture';

UPDATE study SET content_markdown = '# 실시간 학생 Presence 추적 및 이상 행동 감지 시스템 구축\n\n## 1. 기술 배경 및 해결하고자 한 핵심 문제\n- 교사용 대시보드에서 수천 명 규모 학생들의 실시간 접속 상태(온라인, 오프라인, 자리비움, 백그라운드) 및 이상 학습 패턴을 수집해야 했습니다.\n- 수천 명의 학생 연결을 상시 유지하기 위한 커넥션 비용(WebSocket)을 절감하면서도, 실시간으로 교사가 학생의 학습 이상 징후를 감지하고 개입할 수 있는 가벼운 메트릭 인프라가 필요했습니다.\n\n## 2. 기술 동작 원리 및 아키텍처 설계\n- **경량 Presence 추적 API 및 Ping/Pong 타임아웃 윈도우**:\n  - 1분 주기의 경량 HTTP Ping/Pong 기반 텔레메트리 파이프라인을 설계했습니다.\n  - Redis ZSET / Hash 기반의 슬라이딩 윈도우 타임아웃을 적용해 일정 주기 동안 핑이 수신되지 않는 세션을 오프라인으로 자동 판정했습니다.\n- **이상 행동 알림 (`manageable-action`) 비동기 규칙 엔진**:\n  - 학생의 문제풀이 지연이나 연속 스킵 같은 이상 이벤트를 SQS 큐로 비동기 수집하고, 백그라운드 Consumer 모듈에서 정량적 규칙(Threshold Rule)을 실시간 평가하도록 구성했습니다.\n- **실시간 호출 및 개입 API (Hexagonal Architecture)**:\n  - 교사가 특정 학생에게 풀이를 요청하는 실시간 이벤트 호출 구조를 헥사고날 아키텍처에 맞춰 도메인 캡슐화했습니다.\n\n## 3. 핵심 구현 및 트러블슈팅 인사이트\n- **커넥션 비용 최적화**: 웹소켓 없이도 Redis In-Memory 인덱싱을 통해 수천 명의 동시 접속 세션을 서버 리소스 부하 최소화 상태로 추적했습니다.\n- **이상 감지 파이프라인**: 핑 수신과 통계 평가를 비동기로 격리해 메인 API 성능에 영향을 주지 않고 실시간 알림 시스템을 안착시켰습니다.'
WHERE slug = 'realtime-student-presence-and-monitoring';

UPDATE study SET content_markdown = '# 제출 문항 도메인의 CQRS 리팩토링 및 6만 건 데이터 마이그레이션\n\n## 1. 기술 배경 및 해결하고자 한 핵심 문제\n- 누적되는 제출 문항(`SubmittedProblem`) 데이터 볼륨 증가로 인해, 조회성 대시보드 API가 단일 컬렉션을 집계 조회하면서 쿼리 응답 속도가 지속적으로 지연되는 성능 병목이 발생했습니다.\n- 쓰기 트래픽(학생의 답안 제출)과 읽기 트래픽(교사/학원의 통계 대시보드 조회)의 성격이 완전히 달라 쓰기 작업이 읽기 쿼리의 락/리소스 경합을 유발하는 구조적 개선이 시급했습니다.\n\n## 2. 기술 동작 원리 및 아키텍처 설계\n- **CQRS 패턴 적용 (Read/Write 모델 상호 격리)**:\n  - 쓰기 도메인과 읽기 집계 도메인을 수평 분리했습니다.\n  - 기존 단일 컬렉션을 학급(`class-submitted-problem`), 학생(`student-submitted-problem`), 전체(`total-submitted-problem`), 학원(`academy-submitted-problem`) 4개의 읽기 전용 통계 전용 도메인으로 수평 재설계했습니다.\n- **무중단 MongoDB Multi-Document 트랜잭션 마이그레이션**:\n  - 14개 핵심 통계 지표(제출수, 정답수, 소요시간 등)를 집계 이관하는 파이프라인 배치 스크립트를 수립했습니다.\n  - 트랜잭션을 세분화하여 마이그레이션 실패 시 자동 롤백 및 재시도가 가능하도록 안전 장치를 마련했습니다.\n\n## 3. 핵심 구현 및 트러블슈팅 인사이트\n- **조회 쿼리 튜닝**: 읽기 전용 통계 컬렉션을 분리함으로써 대시보드 응답 속도를 수초 대에서 10ms 이하로 즉시 개선했습니다.\n- **정합성 유지 인사이트**: CQRS 읽기 모델 동기화 시 이벤트 기반 비동기 갱신을 적용하여 쓰기 응답 속도 지연을 완전히 방지했습니다.'
WHERE slug = 'cqrs-refactoring-and-data-migration';

UPDATE study SET content_markdown = '# Spring Boot 백오피스 서버 단독 구축 및 Redis 세션 기반 크로스도메인 해결\n\n## 1. 기술 배경 및 해결하고자 한 핵심 문제\n- 여러 부서의 무료체험 유입 추적 및 프로모션 관리가 엑셀 및 수기 프로세스로 운영되어 중복 데이터 발생과 행정 리소스 낭비가 컸습니다.\n- 사내 백오피스 시스템 구축 시 독립된 도메인 환경 간 교차 사이트 요청(CORS)에서 세션 쿠키가 탈락하는 보안 이슈를 해결해야 했습니다.\n\n## 2. 기술 동작 원리 및 아키텍처 설계\n- **Spring Boot 3.2 + Security 헥사고날 구조**:\n  - 8개 핵심 도메인과 144개 클래스 규모의 백오피스 아키텍처를 1인 단독 설계했습니다.\n  - NCP 카카오 알림톡 연동 시 자바 표준 암호화 라이브러리로 HMAC-SHA256 헤더 서명 생성기를 구현했습니다.\n- **Redis Session 분산 인증 및 SameSite Cookie 튜닝**:\n  - 독립 배포된 브라우저 도메인 간 인증 쿠키 전달을 위해 Redis Session 스토어를 연동했습니다.\n  - Nginx 서브프록시 레이어에서 `Set-Cookie` 헤더의 `SameSite=None; Secure` 옵션을 정합 제어해 크로스 도메인 인증 차단 문제를 해결했습니다.\n- **컨테이너 오케스트레이션 및 로깅**:\n  - Docker Compose로 MySQL, Redis, Nginx Basic Auth 프록시, Grafana 로깅 뷰어를 단독 구동 환경으로 통합 구축했습니다.\n\n## 3. 핵심 구현 및 트러블슈팅 인사이트\n- **크로스 도메인 세션 이월**: 브라우저 보안 정책 상 세션 탈락 원인을 Nginx 및 Spring Session 계층에서 분석 및 해결해 안정적 1회 로그인 SSO 환경을 구축했습니다.\n- **알림톡 서명 보안**: HMAC-SHA256 암호화 연동으로 외부 서드파티 알림 통신의 위변조를 완벽히 방지했습니다.'
WHERE slug = 'spring-boot-backoffice-and-session-auth';

UPDATE study SET content_markdown = '# 사내 공용 라이브러리 모노레포 구축 및 CLI 스캐폴딩 도구 개발\n\n## 1. 기술 배경 및 해결하고자 한 핵심 문제\n- 마이크로서비스(BFF, Core Application, Common Problem 등) 추가 구축 과정에서 공통 인프라 설정 코드(MongoDB 연동, Redis 지수백오프, SQS PubSub 래퍼)와 예외 핸들러가 복사-붙여넣기 형태로 파편화되었습니다.\n- 신규 백엔드 모듈 개발 시 초기 보일러플레이트 구축에 많은 시간이 소요되고 코드 리뷰 규칙이 흩어지는 문제를 해결하고자 했습니다.\n\n## 2. 기술 동작 원리 및 아키텍처 설계\n- **npm workspaces 기반 모노레포 패키지 아키텍처**:\n  - 코드를 3개 레이어로 분리 패키지화 (`@susimdal/common` 예외/HTTP, `@susimdal/core` NestJS 서버 부트스트랩, `@susimdal/infra` MongoDB/Redis/SQS).\n  - GitHub Packages Private Registry로 버전 관리 및 배포 자동화 구현.\n- **스캐폴딩 CLI 도구 (`@susimdal/cli`)**:\n  - Node.js Commander 기반 CLI 도구를 개발하여 `susimdal new <service-name>` 명령어 한 줄로 Dockerfile, Task Definition, GitHub Actions CI/CD 파일이 포함된 템플릿이 자동 스캐폴딩되도록 구현했습니다.\n\n## 3. 핵심 구현 및 트러블슈팅 인사이트\n- **아키텍처 표준화 인사이트**: 전사 마이크로서비스의 예외 코드(9977-9999) 및 HTTP 인터셉터 패턴을 통일하여 코드 파편화를 방지했습니다.\n- **개발 생산성 제고**: 신규 백엔드 모듈 셋업 시간을 수일에서 수분으로 단축시켜 개발속도와 품질을 동시에 확보했습니다.'
WHERE slug = 'common-packages-and-cli-scaffolding';

UPDATE study SET content_markdown = '# Playwright 브라우저 자동화를 통한 네이버 카페 보안 세션 우회 및 E2E 답변 자동화\n\n## 1. 기술 배경 및 해결하고자 한 핵심 문제\n- 고객 지원 효율화를 위해 네이버 카페 게시판의 고객 문의에 자동 답변을 등록하는 파이프라인이 요구되었습니다.\n- 네이버 로그인 보안 정책(CAPTCHA, 2단계 인증)으로 단순 HTTP request 세션 유지가 불가하며 세션이 자주 만료되어 수동 개입이 수반되는 난제를 해결해야 했습니다.\n\n## 2. 기술 동작 원리 및 아키텍처 설계\n- **Playwright 기반 OTP 로그인 워커 설계**:\n  - Headless 브라우저 제어용 Node.js browser-worker를 구축하고, OTP 일회용 번호 입력 기반 로그인 파이프라인을 자동화했습니다.\n- **AES/GCM 세션 쿠키 암호화 및 헬스 체크**:\n  - 브라우저 컨텍스트에서 `NID_AUT`, `NID_SES` 세션 쿠키를 추출해 AES/GCM 암호화 후 DB에 안전하게 보관했습니다.\n  - 주기적 헬스 체크로 세션 유효성을 자동 판단해 만료 시 슬랙 알림 발송 및 워크플로우 통제를 적용했습니다.\n- **DOM 조작 기반 E2E 답글/멘션 등록**:\n  - 모바일 카페 DOM 조작 및 HTML innerHTML 주작을 통해 특정 멘션 태그 구조를 강제 주입해 자동 답변 수신자 지정을 완수했습니다.\n\n## 3. 핵심 구현 및 트러블슈팅 인사이트\n- **보안 탐지 우회**: CAPTCHA 챌린지를 스마트폰 OTP 번호 입력으로 일원화해 세션 갱신을 10초 내로 처리했습니다.\n- **E2E 답변 자동화**: 무중단으로 네이버 카페 고객 문의 수집 및 답변/대댓글 매핑 E2E 자동화를 완수하여 리드타임을 수분 이내로 단축했습니다.'
WHERE slug = 'naver-cafe-session-playwright-automation';

UPDATE study SET content_markdown = '# 이메일 및 카페 문의의 다형적 통합 수집과 헤더 기반 스레딩/상태 제어 엔진 구축\n\n## 1. 기술 배경 및 해결하고자 한 핵심 문제\n- 이메일, 네이버 카페 등 다양한 소통 채널에서 고객 문의가 수집될 때, 동일 사용자의 회신이나 연관 메일이 개별 건으로 무작위 적재되어 상담원의 중복 답변과 컨텍스트 혼선이 발생했습니다.\n- 이를 해결하기 위해 비정형 문의 데이터를 단일 스레드로 통일하고 추가 회신 시 문의 상태를 자동으로 제어하는 스레딩 엔진을 개발했습니다.\n\n## 2. 기술 동작 원리 및 아키텍처 설계\n- **In-Reply-To / References 헤더 추적**:\n  - 이메일 헤더의 Message-ID 관계를 분석해 이전 메일의 부모 ID를 추적하고 자식 문의로 자동 묶어내는 계층형 모델을 구축했습니다.\n- **Heuristic 발신자 해싱 및 제목 정규화**:\n  - 헤더 유실 예외 상황에 대응하여, 회신 접두사(Re:, Fwd:)를 정규화하고 발신자 이메일을 HMAC-SHA256 해싱(`email_sender_hash`)으로 인덱싱 조회해 최근 연관 문의를 자동 결속했습니다.\n- **스레드 상태 전이 및 Audit Log 로깅**:\n  - 해결(RESOLVED) 문의에 회신이 들어오면 자동으로 상태를 OPEN으로 전환하고 시스템 감사 로그(`InquiryWorkLog`)를 자동으로 기록했습니다.\n\n## 3. 핵심 구현 및 트러블슈팅 인사이트\n- **스레드 통일**: 파편화된 이메일 회신들을 하나의 문의 히스토리로 정돈하여 중복 상담 리소스를 완벽히 제거했습니다.\n- **누락 제어**: 회신 유입 시 자동 재오픈 상태 전이 파이프라인으로 고객 누락 문의를 0건으로 제어했습니다.'
WHERE slug = 'inquiry-thread-parsing-and-automatic-mapping';

UPDATE study SET content_markdown = '# JPA Converter와 HMAC 해싱을 통한 개인정보(PII) 암호화 및 무중단 데이터 마이그레이션\n\n## 1. 기술 배경 및 해결하고자 한 핵심 문제\n- 고객 문의 본문, 이메일, 연락처 등 개인정보(PII)를 DB에 평문 저장하는 리스크를 방지하고자 컴플라이언스 기준의 DB 암호화가 필요했습니다.\n- 이미 대량의 데이터가 적재된 환경에서 서비스 중단 없이 하위 호환성을 유지하며 데이터를 이관하는 마이그레이션 전략이 핵심이었습니다.\n\n## 2. 기술 동작 원리 및 아키텍처 설계\n- **JPA Attribute Converter 기반 AES/GCM 암복호화**:\n  - 영속성 계층에서 자동 작동하는 `EncryptedStringConverter`를 개발하고 매 암호화 시 랜덤 IV를 적용해 AES/GCM 보안성을 확보했습니다.\n- **등치 검색용 HMAC-SHA256 해시 컬럼**:\n  - AES/GCM 암호문의 일치 검색 불가능 한계를 해결하기 위해 발신자 이메일을 HMAC-SHA256으로 해싱한 `email_sender_hash` 전용 컬럼을 구성했습니다.\n- **무중단 관용적 복호화 및 배치 이관**:\n  - 복호화 실패 시 평문을 안전하게 반환하는 하위 호환 복호화(`decryptOrPassThrough`)를 도입해 무중단 이관 파이프라인을 완료했습니다.\n\n## 3. 핵심 구현 및 트러블슈팅 인사이트\n- **보안 컴플라이언스**: DB 유출 시에도 민감 정보 노출을 완벽히 차단하는 암호화 규격을 완성했습니다.\n- **무중단 이관**: 기존 적재 데이터를 유실 없이 100% 암호화 마이그레이션하는 데 성공했습니다.'
WHERE slug = 'db-level-pii-encryption-and-migration';

UPDATE study SET content_markdown = '# Azure 로그 비용 과다 진단 및 보관 기간 최적화 (RET-001, RET-002)\n\n## 1. 기술 배경 및 해결하고자 한 핵심 문제\n- 클라우드 환경에서 시스템 규모가 커짐에 따라 수집되는 로그 데이터 양이 급증하고, 이로 인해 Log Analytics Workspace(LAW) 청구 비용이 예측 불가능하게 늘어나는 ''빌링 쇼크(Billing Shock)''가 빈번히 발생했습니다.\n- 로그 요금 최적화를 위해서는 전체 수집을 막는 것이 아니라, 어떤 테이블에서 비용이 발생하는지(`Usage` 분석)와 보존 주기(Retention) 및 요금제(Plan)가 가치에 맞게 설정되었는지 진단하고 처방하는 지능형 모니터링이 필요했습니다.\n\n## 2. 기술 동작 원리 및 아키텍처 설계\n- **Usage 테이블 기반 실시간 비용 추적 (RET-001)**:\n  - `Usage` 시스템 테이블을 쿼리하여 실제 과금 대상인 테이블 (`IsBillable == true`)의 데이터 크기 (`Quantity` 및 `_BilledSize`)를 DataType별로 정렬 및 분석하는 KQL 수집 모듈 구현.\n- **Azure Retail Prices API 실시간 연동**:\n  - 리소스가 배포된 Azure 리전 속성을 식별하고, 해당 리전의 `Analytics Logs Data Ingestion` Pay-As-You-Go 단가를 동적으로 API 호출하여 정확한 비용을 USD로 환산.\n  - 리전별 단가 조회 오버헤드를 낮추기 위해 24시간 TTL 인메모리 캐시 설계.\n- **ARG(Azure Resource Graph) 기반 동적 예산 수집**:\n  - `workspaceCapping.dailyQuotaGb` 설정을 Resource Graph로 Bulk 조회하여 일일 예산 자동 계산.\n- **테이블 등급별 보존 주기 최적화 시뮬레이션 (RET-002)**:\n  - 로그 성격에 따른 분류 체계(Class A 보안/감사, Class B 운영/지표, Class C 추적/디버그) 정의.\n  - 테이블별 현재 보존일수와 사용량을 기준 31일 초과분에 대한 Archive 티어 전환 시 월간 예상 절감 비용 산출.\n\n## 3. 핵심 구현 및 트러블슈팅 인사이트\n- **사전 방어 파이프라인**: 일일 예산 대비 현재 소진율(`budget_ratio`)을 계산해 10% Warning, 25% Critical 경보를 발송하여 요금 폭탄을 사전 방지했습니다.\n- **컴플라이언스 양립**: 보안 로그 365일 규정 준수와 불필요한 디버그 로그의 Archive 티어 전환 처방을 동시에 달성했습니다.'
WHERE slug = 'azure-log-cost-retention-optimization';

UPDATE study SET content_markdown = '# 클라우드 인프라 생존 및 앱 관측성 진단 아키텍처 (DET-001, DET-002, DET-003)\n\n## 1. 기술 배경 및 해결하고자 한 핵심 문제\n- 분산 인프라 환경에서 리소스(VM, App Service 등)는 정상 가동 중이나 로그 에이전트가 중단되어 모니터링 사각지대가 발생하는 문제를 해결해야 했습니다.\n- 계정 정보나 Secret 키를 직접 수집하지 않는 보안 제약 하에, Log Analytics Workspace 텔레메트리만으로 관측 배관의 유효성과 앱 헬스 상태를 간접 판정하는 지능형 모듈을 설계했습니다.\n\n## 2. 기술 동작 원리 및 아키텍처 설계\n- **명시 연결 기반 Target Resolver (DET-001)**:\n  - Diagnostic Settings 및 hidden-link 메타데이터 등 명시적 연결 경로만 추적하여 신뢰도를 확보.\n  - App Service/ACA/ACI를 대상으로 `AppRequests`, `AppTraces` 유입 상태를 추적.\n- **VM 관측성 배관 진단 및 생존 분석 (DET-002)**:\n  - DCR Association 정보와 AMA(Azure Monitor Agent) 설치 여부를 교차 검증.\n  - `Heartbeat` 수신 상태와 Host Name을 기반으로 앱 후보군 매핑.\n- **HTTP 헬스 신호 및 응답 지연 탐지 (DET-003)**:\n  - `AppRequests` 테이블에서 헬스체크 봇, AlwaysOn 노이즈 요청을 제외한 정제 쿼리 적용.\n  - 24시간 에러율(HTTP 5xx)과 P95 응답 속도(`percentile(DurationMs, 95)`) 자동 산출.\n\n## 3. 핵심 구현 및 트러블슈팅 인사이트\n- **배관 진단**: LAW 미연결 시 Critical, 플랫폼 로그만 유입 시 Warning, 관측성 완비 시 Healthy 단계별 진단 정착.\n- **장애 탐지**: 에러율 > 15% 또는 P95 Latency > 5,000ms 기반의 자동 경보 체계로 모니터링 대시보드 시각화 완수.'
WHERE slug = 'cloud-infrastructure-app-observability-diagnostics';

UPDATE study SET content_markdown = '# 지능형 로그 필터링 및 민감 정보 마스킹 엔진 (PRV-001, PRV-002, PRV-003, FLT-001, FLT-002, FLT-003)\n\n## 1. 기술 배경 및 해결하고자 한 핵심 문제\n- 개발 단계의 디버그 로그가 프로덕션에 방치되어 불필요한 청구 비용이 발생하거나, 사용자 계정 정보(비밀번호, 토큰 등)가 평문 수집되어 컴플라이언스를 위반하는 리스크를 방지하고자 했습니다.\n- 무의미한 노이즈 로그의 유입을 막고, 에러 로그의 3대 필수 컨텍스트(Cause, Location, Action) 보유 여부를 정량적으로 점수화하는 엔진을 구현했습니다.\n\n## 2. 기술 동작 원리 및 아키텍처 설계\n- **운영 환경 디버그 로그 방치 감지 (PRV-001)**:\n  - App Settings 환경변수와 KQL `SeverityLevel <= 1` 유입 상태를 교차 검증해 하드코딩된 디버그 로거 판별.\n- **PII(개인정보) 감지 및 실시간 마스킹 (FLT-001)**:\n  - 이메일, 전화번호, API Token 정규식 패턴을 정의하고 LAW 조회 단계에서 즉시 마스킹 수행.\n- **고빈도 노이즈 지문 분석 및 DCR KQL 생성 (PRV-002, FLT-003)**:\n  - 앞 150글자 지문(Fingerprint) 기반 상위 노이즈 패턴 추출 및 LLM 활용 DCR Transformation KQL 생성.\n- **에러 로그 컨텍스트 품질 점수화 (FLT-002)**:\n  - Cause(예외 타입), Location(스택트레이스), Action(조치 힌트) 3요소 품질 평가 점수화.\n\n## 3. 핵심 구현 및 트러블슈팅 인사이트\n- **보안 & 비용 동시 확보**: PII 마스킹을 통한 컴플라이언스 준수와 노이즈 로그 필터링을 통한 비용 절감을 동시에 달성했습니다.\n- **디버깅 SNR 최적화**: 에러 로그 3요소 평가를 통해 실무 개발팀의 장애 조치 리드타임을 대폭 감소시켰습니다.'
WHERE slug = 'intelligent-log-filtering-pii-masking-engine';
