apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account-api.yaml
  - service-account-worker.yaml
  - deployment.yaml
  - deployment-worker.yaml
  - network-policy.yaml
  - service.yaml
  - service-worker.yaml
