apiVersion: v1
kind: Service
metadata:
  name: self-intro-backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: self-intro-backend
  ports:
    - name: http
      port: 8080
      targetPort: http
