apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: self-intro
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.self-intro.svc.cluster.local:9090
        isDefault: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.self-intro.svc.cluster.local:3100
        jsonData:
          derivedFields:
            - matcherType: regex
              matcherRegex: "(?:traceId|trace_id)=(\\w+)"
              name: TraceID
              url: '$${__value.raw}'
              datasourceUid: tempo
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo.self-intro.svc.cluster.local:3200
        uid: tempo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: self-intro
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
      containers:
        - name: grafana
          image: docker.io/grafana/grafana:11.0.0
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-admin-secret
                  key: GF_SECURITY_ADMIN_USER
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-admin-secret
                  key: GF_SECURITY_ADMIN_PASSWORD
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: datasources-volume
              mountPath: /etc/grafana/provisioning/datasources
            - name: dashboards-provider-volume
              mountPath: /etc/grafana/provisioning/dashboards
            - name: dashboards-json-volume
              mountPath: /var/lib/grafana/dashboards
            - name: grafana-data
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-data
          emptyDir: {}
        - name: datasources-volume
          configMap:
            name: grafana-datasources
        - name: dashboards-provider-volume
          configMap:
            name: grafana-dashboards-provider
        - name: dashboards-json-volume
          configMap:
            name: grafana-dashboards-json
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: self-intro
spec:
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  selector:
    app: grafana
