apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: self-intro

resources:
  - prometheus.yaml
  - loki.yaml
  - alloy.yaml
  - grafana.yaml
  - grafana-ingress.yaml
  - node-exporter.yaml
  - kube-state-metrics.yaml

configMapGenerator:
  - name: grafana-dashboards-provider
    files:
      - dashboards-provider.yaml=grafana-dashboards-provider.yaml
  - name: grafana-dashboards-json
    files:
      - rabbitmq-overview.json
      - mysql-overview.json
      - oracle-atp-overview.json
      - node-overview.json
      - pod-overview.json
