apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: self-intro

resources:
  - storageclass.yaml
  - prometheus.yaml
  - loki.yaml
  - alloy.yaml
  - grafana.yaml
  - grafana-ingress.yaml
  - node-exporter.yaml
  - kube-state-metrics.yaml
  - tempo-configmap.yaml
  - tempo.yaml

configMapGenerator:
  - name: grafana-dashboards-provider
    files:
      - dashboards-provider.yaml=grafana-dashboards-provider.yaml
  - name: grafana-dashboards-json
    files:
      - rabbitmq-overview.json
      - mysql-overview.json
      - oracle-atp-overview.json
      - node-overview.json
      - pod-overview.json
      - spring-boot-statistics.json
      - app-logs.json
      - redis-overview.json
      - ingress-nginx-overview.json
      - ai-worker-business-ops.json
