apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: self-intro
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200
      grpc_listen_port: 9095

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318

    storage:
      trace:
        backend: s3
        wal:
          path: /var/tempo/wal
        s3:
          bucket: ${TEMPO_S3_BUCKET}
          endpoint: ${OCI_S3_ENDPOINT}
          region: ${OCI_S3_REGION}
          access_key: ${OCI_S3_ACCESS_KEY_ID}
          secret_key: ${OCI_S3_SECRET_ACCESS_KEY}
          forcepathstyle: true
          insecure: false

    compactor:
      compaction:
        block_retention: 48h
