plugins {
    id 'java-library'
}

dependencies {
    api project(':core')
    api 'org.springframework.ai:spring-ai-starter-model-openai'
    api 'org.jsoup:jsoup:1.17.2'
    api 'com.microsoft.playwright:playwright:1.52.0'
    
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}
