apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/mysql-exporter
  # generate-sealed-secret.sh 실행해서 sealed-secret.yaml 만든 다음 아래 줄 추가할 것
  # - sealed-secret.yaml
