---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysqld-exporter-secret
  namespace: self-intro
spec:
  encryptedData:
    .my.cnf: AgAEvq4Tpx4ig6tKtL46O1waU/z2Yd45Ji5jCqC/9pKiO1RbCQhNn3uwQJrkW96/7y2v6nqW+Tzgl1nWO1qvnq3fYd0sZlwfxkaxe/rwCj0yYb4GbRE6IeIOagfVh0dZwVonzuZ1ricXRzhAWQbOSoMBc0BIe1bbiRjD/Bsjz3jm5WhO+94uzVv92Qc4+6smb/SOLRnCcZe2KZp7jTbn4Tx9Rh7B71L8OTLPZIwssM5Ja7IKHms4ux75fo7JeZszTbAxkpyJn35rxYxVpod0qDlWVq2dcctWYJLxOB7CSUV1Uy0m6AihvLEFPFtpw2Mj/y5MMsdPtG2rZNZoJoRJMhkUyiER1fgtOA/b44KtuekkqpbWIMYXTQOV/+KrgeSQFCzE/1+wld/DS05vRbNRLSIhhPoWEbuCe8lpSNhrlmODLEO1KhNntoI/mNEOtcfpeCPhIA12YIHNq/NWn/XfnNVHKMqaOsLg0buzSrFZ6cg+3/sPd5klcY8joIUDG1tUN9mhbbJ2fHTJa4VfK+54ndakfhoTRkzlzok90XLt8rnpdmYr31eQHe9PHEv0rkni6eV0Hcr+dBzni4WsVykhzDUGMxjPutonpNlofb7YVi8d6BwqKd3asI0g0//VREjSDlokI3lQfYdq5solCrEPvne/honWCZt91drOE1GTVKW0ZExCBJNoSdhLIhHnvJpQF+9Zce8aBpuWvgMS94aoZ+F9kxK1RwSNGt/SVHF9rOjUBNQj6wcejc7a7qsOetbC3CdIi3xo2KhRoe5lyEeb7LNEyi7Xg/iqq2UZ
  template:
    metadata:
      name: mysqld-exporter-secret
      namespace: self-intro
    type: Opaque
