-- Oracle 26ai Autonomous Database (selfintroworker) Schema & Vector Index Definition
-- Oracle 26ai 전용 Native VECTOR 데이터 타입 및 HNSW (In-Memory Neighbor Graph) 인덱스 스키마 정의

-- 1. 채용공고 텍스트 청크 및 임베딩 벡터 테이블
-- 임베딩 모델: NVIDIA NIM nvidia/nemotron-3-embed-1b (2048차원)
CREATE TABLE IF NOT EXISTS job_posting_vector (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_posting_id NUMBER NOT NULL,
    chunk_content CLOB NOT NULL,
    embedding_vector VECTOR(2048, FLOAT32) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE VECTOR INDEX IF NOT EXISTS idx_job_posting_vector_hnsw 
ON job_posting_vector (embedding_vector) 
ORGANIZATION INMEMORY NEIGHBOR GRAPH 
DISTANCE COSINE;

-- 2. 내 경험/프로젝트 텍스트 청크 및 임베딩 벡터 테이블
CREATE TABLE IF NOT EXISTS experience_vector (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id NUMBER NOT NULL,
    experience_id NUMBER NOT NULL,
    chunk_content CLOB NOT NULL,
    embedding_vector VECTOR(2048, FLOAT32) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

DECLARE
    column_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO column_count
    FROM user_tab_columns
    WHERE table_name = 'EXPERIENCE_VECTOR' AND column_name = 'WORKSPACE_ID';
    IF column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE experience_vector ADD workspace_id NUMBER DEFAULT 1 NOT NULL';
    END IF;
END;
/

CREATE VECTOR INDEX IF NOT EXISTS idx_experience_vector_hnsw 
ON experience_vector (embedding_vector) 
ORGANIZATION INMEMORY NEIGHBOR GRAPH 
DISTANCE COSINE;

-- 3. 기술 스터디 마크다운 청크 및 임베딩 벡터 테이블
CREATE TABLE IF NOT EXISTS study_vector (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id NUMBER NOT NULL,
    study_id NUMBER NOT NULL,
    chunk_content CLOB NOT NULL,
    embedding_vector VECTOR(2048, FLOAT32) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 기존 단일 Workspace 벡터는 bootstrap Workspace(id=1) 소유로 보존한다.
-- 신규 동기화부터는 이벤트의 실제 workspace_id를 사용한다.
DECLARE
    column_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO column_count
    FROM user_tab_columns
    WHERE table_name = 'STUDY_VECTOR' AND column_name = 'WORKSPACE_ID';
    IF column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE study_vector ADD workspace_id NUMBER DEFAULT 1 NOT NULL';
    END IF;
END;
/

CREATE INDEX IF NOT EXISTS idx_study_vector_workspace_study
ON study_vector (workspace_id, study_id);

CREATE VECTOR INDEX IF NOT EXISTS idx_study_vector_hnsw 
ON study_vector (embedding_vector) 
ORGANIZATION INMEMORY NEIGHBOR GRAPH 
DISTANCE COSINE;
