-- Oracle 26ai Autonomous Database (selfintroworker) Schema & Vector Index Definition
-- Oracle 26ai 전용 Native VECTOR 데이터 타입 및 HNSW (In-Memory Neighbor Graph) 인덱스 스키마 정의

-- 1. 채용공고 텍스트 청크 및 임베딩 벡터 테이블
CREATE TABLE IF NOT EXISTS job_posting_vector (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_posting_id NUMBER NOT NULL,
    chunk_content CLOB NOT NULL,
    embedding_vector VECTOR(1536, FLOAT32) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 2. Oracle 26ai HNSW (In-Memory Neighbor Graph) 코사인 유사도 초고속 벡터 인덱스
-- 1536차원 벡터 간 코사인 거리(COSINE) 탐색 속도를 0.001초 미만으로 최적화합니다.
CREATE INDEX IF NOT EXISTS idx_job_posting_vector_hnsw 
ON job_posting_vector (embedding_vector) 
ORGANIZATION INMEMORY NEIGHBOR GRAPH 
DISTANCE COSINE;
