apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-auth-secret
  namespace: self-intro
spec:
  encryptedData:
    MFA_ENCRYPTION_KEY: AgAHZn58cYWOhFDOwd1BTXf8bLcms5u0droju6ziqcSEzJvLcnD0n9dND3YLoh6oD1t6sPnIi5OTf+BrS6EONJ38Ks/ehmaskTAgTuE8k4xGV/NuIV3QPxBGco1lltu6OGqxy1hz5U3GHBxOclf01X5AbvzVRWH/WPd3fBeAoTJwbokdsYslBDnLaaJdOstSawYwVDg/49j9uEOEWLxwj/mF464tst6DqxTICjRpylvJg+S9YJpjrt+uPjYpC8IlV2g6PQd8x5BmN+v3b0sX+FwKj/fEdblM/uRuuiVcS3fFWVjqGpx9tnN3ShjzxvTZqVuJuquBe4++7ydCC/K40D00cnn1M7Se7VjeMERO7goeAE5RkOr8xoGYDW2aGp/kn9UOXZyuf/JWn0RfU85eXNYPwgvhpoutuZZYJ2GwL7Nkd/OaLvB3jJVA+nPQw6I1PzunyZSglQsky9weUvHCTde7tm7bagnnqp56i9MzfJu1wEUctI78uZPUkvC4V8D0HoQXilzd4Gd+boOPduemrJSnhyaRWxGD2XfST2/bpGn/WKW2zASKf+ywYqofp81h5Ko7jxpDxC6c97xF0Vn6GLRxC5moQmQ8TVZeWRb6I2DJhOnKae4BvEYI104gE3KiGdBxcK3zOsnppSwHe2ql6HNCvTuw0vRO3PSaeIyORR9tNH5me47kUVkYxcOiP1MDBvzYf8QzL1JqiUDYg5TK51S/RZmwJKrANiGARlzbdSQN41SdlTUGY9HmcAyu9w==
  template:
    metadata:
      name: backend-auth-secret
      namespace: self-intro
    type: Opaque
