---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-ai-secret
  namespace: self-intro
spec:
  encryptedData:
    NVIDIA_API_KEY: AgDKk6RDgOw9QoT47C+R+kQqknwKehZbMpbX60RIrXdamcilxDLfk2mZJtnp0QlvqYEFaZtQVRCuXN2uGGHaOR1G+Pz9WcYtq8lEQ49VKP71uMdrUiA7CpiIosRpdg4SipXGk2hFVo5oCCipktx4UnOYW4hYiO9P1POnzFvpqbYcEhwOrvK1ATln52ZG1BGPWHiNQwP2EvaltYlcfGFxdk/d8d9CFIKHHOxQ82unyRlCW+6CikqRd4ZDx1czsOSuy/AdW3JTFRJB6jgAdvzCXw8XOHZ3TxGh/q0LM+4/Wl6WKuOZtWqNu6rPWYdvzkD4qwvAVa2z1NZs5NUCcjGRE73lVf7KUb5fmbly4VPwOum7qaJoBMgGgbwSvJ5nFgylkzwz5Yi9tN3XFFG3Iu+2gg/ohsel2zAyzlKHezEBqUFotepu9GqaoV1Sj5i0Ayf06EZsm+FR+AtkKq5eZBBea/BnjP8DXFkItg+5wShNTYybGrGAv56Zb0MUMmMX2l6qBkC/ITifKSoe2jcAgGwFbgBUxkFSH30nvCsoLkDtbP5JN7oNBRwkdLbIBPKP03EDtBUYm9JpeE6RODLjk/JHW6cE+lJTrFnAYRtOwE++09fGAMpUDQanmAU0CevSbCS935ACSdw3jj1y4q0kdBRgF3Yt7HV4Uyt0xXiJ7rMkabMQG+0xqnGeXuwn5dN867L71DMlfhrRO/HFfGCcDj0/A1k7r9UzFxpz5utzgu2vJSXAK+3CBl6kmhwNliQLXvQqXMJDgo27H5y3MYCnDoXgWgIPJK2FvxHM
  template:
    metadata:
      name: backend-ai-secret
      namespace: self-intro
