apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-auth-secret
  namespace: self-intro
spec:
  encryptedData:
    MFA_ENCRYPTION_KEY: AgDKBSOUA0dHdsNDRqg7v8IedY6i70pFdOF7+K7URoCOPs0exsYw5LhOTsnT+ZfeSSYzozrSRWy7SoNcoqLEbSf/uzKY5z01/Uo6OPi4vhABE0QekF2G50kveD9ppMMUPZS3/4PIL4DfaAkt3IYcVW4NBMh4iTe4JiXyJKhDT7KyWkSzCVsDcZ1T6oJi8OZbVpG56YyDBHPpg9wIGGCoxEiZ4H9bVcQ1zI4kODtz+WYu4I51PKDE3vOWQ1HjzlumD7KYofkI8/xtE966lpkU7ej5xMLosoJFhYXjHhOK739w5/PMF+zXuL0DSwtOfKwFdF7olu90nSrHBFYH+oML/dlseumGPH37z9RaQrqKSUDD+hFaGsIqq0Jf4/0hNWkK4rJmKK2ZReP4JevCBESNkoKCTye9JI5rj6gLnh4yT53ejFR/lYyhuiasp4HRdr08OXC1r8dGu+hiuSP1Uv7HNlau9pDzMogiJG4whM6SaO+xxeXTEg1f67YBAxf9WCOuXmSAgaweFVFfkCNbnqsns96Ttzb9q0OXVAjWj7b6gf6ZPLvichU7GyAkiaQNTGkrt1QIAwg1r6yUKlYHZKD1XnqUaN3OoImUuZpqjK5qNUHzpE/rbqwytzhNMJewcVZZjt6MrJhKF57E09HsU8hiOmD5HzmkISVw5z2F4VCaIrWImf/L3SxL3D0881SgwVAUwNDyPjmvONX1+p+h9iqoFt5CxxcdDSWEDPmpiIt6NK7xFXdfCUSOoYFKXf6zAoo=
  template:
    metadata:
      name: backend-auth-secret
      namespace: self-intro
    type: Opaque
