---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-storage-secret
  namespace: self-intro
spec:
  encryptedData:
    STORAGE_ACCESS_KEY: AgCB8TsTYpj5q8rSow5h1bOQZvpRsOWjSX0tsOZPe87TtTlFWqwcylvtWdDAEDE31f3c3VRhvwamUl3Qz5cL5NDCkzfZWJlGR2gcrREUWI5Drb9NlCeQ+DY6ZBfn1W5/FkGV+LnEyMITKgadMWMU85qsTNLTrtilmgDsmrxfngDU0tFfvhCtQJXE/k0JeiRAickAHEEd6xhWh6g8UudqUJ1bqSBJWJZshFjyT/kWVplbV3hluYKo+e6sajy9ZajOeTcEI3BKFn3f0zsvxzTFhoSnLzjRk/ua9ps8GN0eH7AbnSWSbGSxh65ohOztf2OCrfdIGY2iqcBo3Sj0QZh9GLNg/QfFxGwVTfQZND61t1CIJbwHeyWCMSviEoXzESVJFoNZCffd0kablTZ6NexjUGbv38CwmUaWigXuWMs46D7vmSRWEpqNzvXjbfp0TmmhTaupNl1AgOrBDArTh0hGuKVSKKKqhu5MYnWJsQyMl95uGa4VSyOAcDxxjDMNUTPp8N0tt3x5p2zbuHtMYTQgRWSfPYTjk+VwRpbMOYcwRlILf0HpLMG+hJ7QsD/5f2f46tQu6L8i4OxrFMDpbuds2hE/uMWnrfIa+2h2UDhLgwgblyr0tkY5SHt0ETJoDfFRIhbKOzUwxcEzSUeT0oRHTQ337hXaKOWlLhTKFnBraYAQvuQmdyatEbJZjAUEJ2qoPWN/wXPd68jCe3kLccSYoLepRsQ184zpbtLrV5fTJflyWfJ3dkvBHBJI
    STORAGE_SECRET_KEY: AgAvtzCBfYqzflSxJjOCbwq0JSKXB6I0AW2fnzNr4dL00nrYNOsAS8qLuNxN6Fxjc4+5WGR4S23KKQ/KZuPcq4PcGxKGxPds+oVTocrU0lgfb2rBVVntbhefrZLFoezWJmGrNDv4AZn4T0jfOg6rzqAqQE8sMBLC970YY5aN9fhYDOdAVmXItDcG3x2yjZ9HcuWYXrVm8IoOUJgCeQ+D2c08+IvNIFGT2mk1ctClAAG6gP1yUqO8S5D9w4/3n3qVMtbuUW7LBNOIlGsIyp/cmfFRlrFfusowCKAW+Gylqfm5+dD4SQ5KP96WImJgRyQX67RS7nHKUFLwJ8cuBXuyJck5wxwJ5GCRPy93X0bXYc0+qjDHfZKuRKEM0CkrFNWa4BY7gjaTQehAeua+XNB/4dQ9Ssynr8NSYoxX/bXzso42tuzbMi6C0Wngzm0m6Yu2VzIZnPwma1/0vYKnGsvuXDKCfmMCsHxtKKNZJO69L3si2ed930EHgjx0rNYxm4rlwxXwrnhLOlWHMV8c2LxH7oPk+QtpiaB2iYa2LQ9LdKTWVgzHX38P8pAmuxrZUAQIaUvoZkzTs4ndj5e9R13ttl/XjKI+d7yy7+uDAoZl1WUxmAyBl2SNaL9m5Qm3as6ddkC6jQBF22eAU7T7jM8GZvlwyHtGZuUTA65oPOk1LbOPKvh9IbODCU37CBakNSUr14itajgH314el/TLVw2lPOBX5yilKkdO6mqSRCsGjBbl3MJgcD+k8kTyMIMxoA==
  template:
    metadata:
      name: backend-storage-secret
      namespace: self-intro
    type: Opaque
