---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-kofi-secret
  namespace: self-intro
spec:
  encryptedData:
    KOFI_VERIFICATION_TOKEN: AgCPmQfZ3XlybBDyxXmrMrfUa3hhl5jmZZChcOKMRE6cFuluOuZZLV33hSTszaGKwPptw7u21iIGjeG5iYHJqybiVTlX1IRNsMGFaE6cx8hwwHM0W+ZMfWtVZKN5FqmnP6eb0C4BE632ZNu0YjyBoOrIudXYs/4TPIocyOWaN3wrCkQSueiOOOdES+OcLQ83obwnCV/v1VfNYDGiX8UHqxIMTCpBO+4pLdw6oju5geyOwpE0Yt7ewg8Lm8R4n5F6wlNCC//8eWrRNSEVYCiynEySMZO9QgEpmQHlNzV2kRY4SxPWFN06zUc9EZkOy3eS9bjPMUye5X6xbyamk6eIlqjdGreflDeFO44Bqz17AQYaR0aEfse+kmlEXcZLUSocgzRxWZCwcFJ9nBxtnzq00WHbQboPsAuXsDSfkoq7vV1avP11m2mwLJBZw18yCVPkmFhLDCwLno9A8L+L4lkpsVkEqutfUvJ58sj14S4MMhypaZgAcsWzCRawSz7e24nEyeCyJXnF6B0pxTwNhDXt64QMkHzW3JcwMDV+m3D5HvsjYBjU6yH0RT+1m1pBvsJ778q8gJgxhSJhZqQ+FyNmxa21XAySzKufPbuJEphVRYJYEGg+lbyu0hqSwkyGPV4btqUdIYnVbqn+DrYh6burN5SEYrEuE7hz+0lxhggyt/NSrnuNUTxHG3IlXohs3HDoNFkuBKm88evhBavVKwy1aEQ/JA1tIGzbNGNrJfy69QNnmO0CFRw=
  template:
    metadata:
      name: backend-kofi-secret
      namespace: self-intro
    type: Opaque
