apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-intro-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: self-intro-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: self-intro-frontend
    spec:
      imagePullSecrets:
        - name: ocir-pull-secret
      containers:
        - name: frontend
          image: self-intro-frontend
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "500m"
              memory: 512Mi
