apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-intro-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: self-intro-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: self-intro-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - name: redis
              containerPort: 6379
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
