apiVersion: v1
kind: Service
metadata:
  name: self-intro-redis
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: self-intro-redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
