-- Local-only, repeatable output preview fixture.
-- Set this to the Workspace under test before running the script.
SET @workspace_slug = _utf8mb4'w-c615a2e49bd84088bf51' COLLATE utf8mb4_unicode_ci;
SET @workspace_id = (SELECT id FROM workspace WHERE slug = @workspace_slug LIMIT 1);

START TRANSACTION;

-- Remove only the previous fixture generated by this script.
DELETE FROM competency
WHERE workspace_id = @workspace_id
  AND title = '[DEMO] 장애를 구조 개선으로 전환하는 역량';

DELETE FROM experience
WHERE workspace_id = @workspace_id
  AND title = '[DEMO] 비동기 학습 처리 프로젝트';

DELETE FROM experience
WHERE workspace_id = @workspace_id
  AND title = '[DEMO] 백엔드 플랫폼 엔지니어';

INSERT INTO experience (
    workspace_id, type, title, period_start, period_end, summary, takeaway,
    display_order, show_on_timeline, timeline_label
)
VALUES (
    @workspace_id,
    'CAREER',
    '[DEMO] 백엔드 플랫폼 엔지니어',
    '2024-01-01',
    '2025-10-17',
    '운영 병목을 측정하고 데이터 접근과 비동기 처리 경계를 개선한 테스트 경력입니다.',
    '측정 가능한 병목부터 찾고 재발 방지 가능한 구조로 전환했습니다.',
    900,
    0,
    'DEMO 경력'
);
SET @career_id = LAST_INSERT_ID();

INSERT INTO career (experience_id, company_name, employment_type, department, role)
VALUES (@career_id, '테스트 스타트업', 'FULL_TIME', '플랫폼팀', '백엔드 엔지니어');

INSERT INTO experience_detail (
    experience_id, content, display_order, situation, task, action_detail, outcome,
    narrative, visible, public_visible, resume_available
)
VALUES
(
    @career_id,
    'MongoDB 실행 계획을 분석하고 인덱스 정책을 정비해 고비용 쿼리를 줄였습니다.',
    0,
    '조회 지연과 CPU·메모리 사용량 증가가 반복됐습니다.',
    '병목 쿼리와 과도한 인덱스를 식별하고 팀 정책을 수립해야 했습니다.',
    'Atlas Profiler와 실행 계획을 기준으로 쿼리·인덱스를 재설계했습니다.',
    '초 단위 조회를 수백~수십 ms 단위로 줄이는 개선을 확인했습니다.',
    '테스트용 STAR 상세 문장입니다.',
    0, 0, 0
),
(
    @career_id,
    '동기 학습 종료 처리를 이벤트 fan-out 구조로 분리했습니다.',
    1,
    '통계 계산과 후속 작업이 한 요청에 묶여 평균 응답이 2.74초였습니다.',
    '사용자 응답 경로와 후속 연산의 장애 경계를 분리해야 했습니다.',
    '내부 이벤트와 독립 Listener를 설계하고 핵심 모듈을 구현했습니다.',
    '평균 응답을 413ms로 단축했습니다.',
    '테스트용 정량 성과 문장입니다.',
    0, 0, 0
);

INSERT INTO experience (
    workspace_id, type, title, period_start, period_end, summary, takeaway,
    display_order, show_on_timeline, timeline_label
)
VALUES (
    @workspace_id,
    'PROJECT',
    '[DEMO] 비동기 학습 처리 프로젝트',
    '2025-01-01',
    '2025-06-30',
    '동기 처리 병목을 이벤트 기반 fan-out으로 전환한 테스트 프로젝트입니다.',
    '실패 격리와 사용자 응답 속도를 함께 고려했습니다.',
    901,
    0,
    'DEMO 프로젝트'
);
SET @project_id = LAST_INSERT_ID();

INSERT INTO project (
    experience_id, career_experience_id, slug, role, contribution_rate, repository_url
)
VALUES (
    @project_id,
    @career_id,
    CONCAT('demo-output-', @workspace_id),
    '아키텍처 설계 및 핵심 모듈 개발',
    80,
    NULL
);

INSERT INTO experience_detail (
    experience_id, content, display_order, situation, task, action_detail, outcome,
    narrative, visible, public_visible, resume_available
)
VALUES (
    @project_id,
    '평균 2.74초의 학습 종료 API를 413ms까지 단축한 출력 미리보기용 항목입니다.',
    0,
    '통계와 후속 작업이 동기 await 체인에 포함돼 있었습니다.',
    '응답 경로에서 후속 연산을 분리해야 했습니다.',
    '이벤트 fan-out과 Listener별 책임 분리를 적용했습니다.',
    '평균 응답 시간이 약 85% 개선됐습니다.',
    '테스트용 프로젝트 상세 문장입니다.',
    0, 0, 0
);

INSERT INTO workspace_skill (
    workspace_id, skill_id, skill_level, skill_version, skill_comment, usage_type,
    is_core, display_order, created_at, updated_at
)
SELECT
    @workspace_id,
    skill.id,
    'INTERMEDIATE',
    NULL,
    '[DEMO OUTPUT PREVIEW]',
    'WORK',
    1,
    900 + ROW_NUMBER() OVER (ORDER BY skill.name),
    NOW(6),
    NOW(6)
FROM skill
WHERE skill.name IN ('Java', 'Spring Boot', 'MongoDB', 'Docker')
  AND NOT EXISTS (
      SELECT 1
      FROM workspace_skill existing
      WHERE existing.workspace_id = @workspace_id
        AND existing.skill_id = skill.id
  );

INSERT INTO competency (
    workspace_id, title, summary, display_order, is_visible, created_at, updated_at
)
VALUES (
    @workspace_id,
    '[DEMO] 장애를 구조 개선으로 전환하는 역량',
    '운영 지표로 병목을 좁히고 데이터·이벤트 경계를 재설계하는 테스트 역량입니다.',
    900,
    0,
    NOW(),
    NOW()
);
SET @competency_id = LAST_INSERT_ID();

INSERT INTO competency_evidence (
    competency_id, experience_id, evidence_summary, is_primary, display_order
)
VALUES (
    @competency_id,
    @career_id,
    'MongoDB 튜닝과 이벤트 기반 처리 개선을 근거로 연결한 테스트 데이터입니다.',
    1,
    0
);

COMMIT;

SELECT @workspace_slug AS workspace_slug,
       @career_id AS demo_career_id,
       @project_id AS demo_project_id,
       @competency_id AS demo_competency_id;
