databases:
  default:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_TNS_ALIAS}
    tnsAdmin: /etc/oracle/wallet
    queryTimeout: 5
    maxOpenConns: 10
    maxIdleConns: 10

metrics:
  default: default-metrics.toml

log:
  destination: /opt/alert.log
  interval: 15s
