apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: self-intro

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: oracledb-exporter-config
    files:
      - config.yaml
